### ISSUE TITLE
API Calls

### ISSUE THREAD

**Issue by vidaaudrey** [trippian/trippian#175]
- [x] putDestination

- [x] getUsers
- [x] getUserById
- [ ] postUser
- [x] deleteUserById
- [x] updateUser

- [x] getTrippianById
- [ ] postTrippian
- [ ] deleteTrippianById
- [ ] updateTrippian

- [x] getInquiries
- [x] getInquiryById
- [x] postInquiry
- [x] deleteInquiryById
- [x] updateInquiry

- [x] getTrips
- [x] getTripById
- [ ] postTrip
- [x] deleteTripById
- [x] updateTrip

**Comment by jlag34** [comment]
Finished
